---
- name: Create RHEL Linux Users
  hosts: rhel
  ansible_user: deployer
  
  tasks:
    - name: 'Add the "col-maet" user'
      ansible.builtin.user:
        name: col-maet
        groups: wheel
        shell: /bin/bash
        local: true
        append: yes
    - name: Modify Authorized Users
      ansible.posix.authorized_key:
        user: col-maet
        
  


